using LLMAPI.Services.Interfaces;
using LLMAPI.Service.Interfaces;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Google.Protobuf;
using Microsoft.Extensions.Configuration;

namespace LLMAPI.Services.OpenRouter
{
    /// <summary>
    /// Service to interact with the OpenRouter API for text generation and image recognition.
    /// Implements interfaces for both text and image services.
    /// </summary>
    public class OpenRouterService : ITextGenerationService, IImageRecognitionService, IImageFileService
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfiguration _configuration;

        /// <summary>
        /// Initializes a new instance of the <see cref="OpenRouterService"/> class.
        /// </summary>
        /// <param name="httpClientFactory">Factory for creating HTTP clients.</param>
        /// <param name="configuration">Application configuration provider.</param>
        public OpenRouterService(IHttpClientFactory httpClientFactory, IConfiguration configuration)
        {
            _httpClientFactory = httpClientFactory;
            _configuration = configuration;
        }

        /// <summary>
        /// Generates text using a specified model and prompt via the OpenRouter API.
        /// </summary>
        /// <param name="model">The LLM model to use for text generation (e.g., "openai/gpt-4o-mini").</param>
        /// <param name="prompt">The text prompt to send to the LLM.</param>
        /// <returns>The generated text response from the LLM or an error message.</returns>
        public async Task<string> GenerateText(string model, string prompt)
        {
            var requestData = new
            {
                model,
                messages = new List<object>
                {
                    new { role = "user", content = prompt }
                }
            };

            return await SendRequest(requestData);
        }

        /// <summary>
        /// Analyzes an image from a given URL using a specified model and prompt via the OpenRouter API.
        /// </summary>
        /// <param name="model">The LLM model to use for image analysis (e.g., "openai/gpt-4o").</param>
        /// <param name="imageUrl">The URL of the image to analyze.</param>
        /// <param name="prompt">The text prompt to guide the image analysis (e.g., "Write an alt text for this image.").</param>
        /// <returns>The image description generated by the LLM or an error message.</returns>
        public async Task<string> AnalyzeImage(string model, string imageUrl, string prompt)
        {
            var requestData = new
            {
                model,
                messages = new List<object>
                {
                    new {
                        role = "user",
                        content = new List<object>
                        {
                            new { type = "text", text = prompt },
                            new { type = "image_url", image_url = new { url = imageUrl } }
                        }
                    }
                }
            };

            return await SendRequest(requestData);
        }

        /// <summary>
        /// Analyzes an image from byte data using a specified model and prompt via the OpenRouter API.
        /// </summary>
        /// <param name="model">The LLM model to use for image analysis.</param>
        /// <param name="imageBytes">The image data as a ByteString.</param>
        /// <param name="prompt">The text prompt to guide the image analysis.</param>
        /// <returns>The image description generated by the LLM or an error message.</returns>
        public async Task<string> AnalyzeImage(string model, ByteString imageBytes, string prompt)
        {
            string base64Image = imageBytes.ToBase64();
            string dataUri = $"data:image/png;base64,{base64Image}";

            var requestData = new
            {
                model,
                messages = new List<object>
                {
                    new {
                        role = "user",
                        content = new List<object>
                        {
                            new { type = "text", text = prompt },
                            new { type = "image_bytes", image_bytes = dataUri }
                        }
                    }
                }
            };

            return await SendRequest(requestData);
        }

        /// <summary>
        /// Sends a request to the OpenRouter API.
        /// </summary>
        /// <param name="requestData">The request data object to be serialized as JSON.</param>
        /// <returns>The content of the successful response from the API, or an error message.</returns>
        private async Task<string> SendRequest(object requestData)
        {
            var openRouterAPIKey = _configuration["OpenRouter:APIKey"];
            var openRouterAPIUrl = _configuration["OpenRouter:APIUrl"];

            var client = _httpClientFactory.CreateClient();

            client.DefaultRequestHeaders.Add("Authorization", $"Bearer {openRouterAPIKey}");
            client.DefaultRequestHeaders.Add("HTTP-Referer", "https://localhost:5256");
            client.DefaultRequestHeaders.Add("X-Title", "AltGen");

            var jsonContent = JsonConvert.SerializeObject(requestData);
            var content = new StringContent(jsonContent, Encoding.UTF8, "application/json");

            var response = await client.PostAsync(openRouterAPIUrl, content);
            var responseContent = await response.Content.ReadAsStringAsync();
            Console.WriteLine("Status code: " + response.StatusCode);
            Console.WriteLine("Response headers: " + response.Headers);
            Console.WriteLine("Raw API response: " + responseContent);

            if (response.IsSuccessStatusCode)
            {
                dynamic jsonResponse = JsonConvert.DeserializeObject(responseContent);
                if (jsonResponse?.error != null)
                {
                    Console.WriteLine("Error details: " + jsonResponse.error);
                    return $"Error: {jsonResponse.error}";
                }

                var imageDescription = jsonResponse?.choices?[0]?.message?.content;
                if (imageDescription != null)
                {
                    return imageDescription.ToString();
                }

                return "No valid content returned from the model.";
            }
            else
            {
                Console.WriteLine($"Error: {response.StatusCode}. Response: {responseContent}");
                return $"Error: {response.StatusCode}. Response: {responseContent}";
            }
        }

        /// <summary>
        /// Converts an <see cref="IFormFile"/> image to a <see cref="ByteString"/>.
        /// </summary>
        /// <param name="imageFile">The image file uploaded via HTTP.</param>
        /// <returns>The image content as a ByteString.</returns>
        public async Task<ByteString> ConvertImageToByteString(IFormFile imageFile)
        {
            using var memoryStream = new MemoryStream();
            await imageFile.CopyToAsync(memoryStream);
            return ByteString.CopyFrom(memoryStream.ToArray());
        }

        /// <summary>
        /// Reads an image from a URL and converts it to a <see cref="ByteString"/>.
        /// </summary>
        /// <param name="url">The URL of the image.</param>
        /// <returns>The image content as a ByteString.</returns>
        public async Task<ByteString> ReadImageFileAsync(string url)
        {
            using HttpClient client = new();
            using var response = await client.GetAsync(url);
            byte[] imageBytes = await response.Content.ReadAsByteArrayAsync();
            return ByteString.CopyFrom(imageBytes);
        }
    }
}
